export const CREATE_NEW_MESSAGE_REQUEST = "CREATE_NEW_MESSAGE_REQUEST";
export const CREATE_NEW_MESSAGE_SUCCESS = "CREATE_NEW_MESSAGE_SUCCESS";
export const CREATE_NEW_MESSAGE_ERROR = "CREATE_NEW_MESSAGE_ERROR";

export const GET_ALL_MESSAGES_REQUEST = "GET_ALL_MESSAGES_REQUEST";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_ERROR = "GET_ALL_MESSAGES_ERROR";

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_ERROR = "DELETE_MESSAGE_ERROR";