export const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE";
export const GET_ALL_MESSAGE = "GET_ALL_MESSAGE";
export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_ERROR = "DELETE_MESSAGE_ERROR";