export const DELETE_SONG_REQUEST = "DELETE_SONG_REQUEST";
export const DELETE_SONG_FAILURE = "DELETE_SONG_FAILURE";

export const SEARCH_SONG_REQUEST = "SEARCH_SONG_REQUEST";
export const SEARCH_SONG_ERROR = "SEARCH_SONG_ERROR";