export const DELETE_SONG_REQUEST = "DELETE_SONG_REQUEST";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";
export const DELETE_SONG_FAILURE = "DELETE_SONG_FAILURE";

export const SEARCH_SONG_REQUEST = "SEARCH_SONG_REQUEST";
export const SEARCH_SONG_SUCCESS = "SEARCH_SONG_SUCCESS";
export const SEARCH_SONG_ERROR = "SEARCH_SONG_ERROR";

export const LIKE_SONG_REQUEST = "LIKE_SONG_REQUEST";
export const LIKE_SONG_SUCCESS = "LIKE_SONG_SUCCESS";
export const LIKE_SONG_ERROR = "LIKE_SONG_ERROR";