export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_ERROR = 'SUBSCRIBE_ERROR';

export const BILLING_PORTAL_REQUEST = 'BILLING_PORTAL_REQUEST';
export const BILLING_PORTAL_SUCCESS = 'BILLING_PORTAL_SUCCESS';
export const BILLING_PORTAL_ERROR = 'BILLING_PORTAL_ERROR';

export const FETCH_SUBSCRIPTION_REQUEST = 'FETCH_SUBSCRIPTION_REQUEST';
export const FETCH_SUBSCRIPTION_SUCCESS = 'FETCH_SUBSCRIPTION_SUCCESS';
export const FETCH_SUBSCRIPTION_ERROR   = 'FETCH_SUBSCRIPTION_ERROR';
