export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const REQUEST_USER = "REQUEST_USER"
export const REQUEST_USER_SUCCESS = "REQUEST_USER_SUCCESS"
export const REQUEST_USER_ERROR = "REQUEST_USER_ERROR"

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_ERROR = "SEARCH_USER_ERROR"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const LOGOUT = "LOGOUT"

export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST"
export const FIND_USER_BY_ID_ERROR = "FIND_USER_BY_ID_ERROR"

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST"
export const FOLLOW_USER_ERROR = "FOLLOW_USER_ERROR"

