export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const REQUEST_USER = "REQUEST_USER"
export const SEARCH_USER = "SEARCH_USER"
export const UPDATE_USER = "UPDATE_USER"
export const LOGOUT = "LOGOUT"

export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST"
export const FIND_USER_BY_ID_ERROR = "FIND_USER_BY_ID_ERROR"

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST"
export const FOLLOW_USER_ERROR = "FOLLOW_USER_ERROR"

