export const STORY_CREATE_REQUEST = 'STORY_CREATE_REQUEST';
export const STORY_CREATE_SUCCESS = 'STORY_CREATE_SUCCESS';
export const STORY_CREATE_FAILURE = 'STORY_CREATE_FAILURE';

export const GET_USERS_FOLLOWED_STORY_REQUEST = 'GET_USERS_FOLLOWED_STORY_REQUEST';
export const GET_USERS_FOLLOWED_STORY_SUCCESS = 'GET_USERS_FOLLOW_SUCCESS';
export const GET_USERS_FOLLOWED_STORY_ERROR = 'GET_USERS_FOLLOW_ERROR';