export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_ERROR = 'CREATE_PLAYLIST_ERROR';

export const GET_USER_PLAYLISTS_REQUEST = 'GET_USER_PLAYLIST_REQUEST';
export const GET_USER_PLAYLIST_SUCCESS = 'GET_USER_PLAYLIST_SUCCESS';
export const GET_USER_PLAYLISTS_ERROR = 'GET_USER_PLAYLIST_ERROR';

export const GET_PLAYLIST_REQUEST = 'GET_PLAYLIST_REQUEST';
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';
export const GET_PLAYLIST_ERROR = 'GET_PLAYLIST_ERROR';

export const GET_PLAYLIST_TRACKS_REQUEST = 'GET_PLAYLIST_TRACKS_REQUEST';
export const GET_PLAYLIST_TRACK_SUCCESS = 'GET_PLAYLIST_TRACK_SUCCESS';
export const GET_PLAYLIST_TRACK_ERROR = 'GET_PLAYLIST_TRACK_ERROR';

export const UPLOAD_SONG_TO_PLAYLIST_REQUEST = 'UPLOAD_SONG_TO_PLAYLIST_REQUEST';
export const UPLOAD_SONG_TO_PLAYLIST_SUCCESS = 'UPLOAD_SONG_TO_PLAYLIST_SUCCESS';
export const UPLOAD_SONG_TO_PLAYLIST_ERROR = 'UPLOAD_SONG_TO_PLAYLIST_ERROR';

export const DELETE_SONG_FROM_PLAYLIST_REQUEST = 'DELETE_SONG_FROM_PLAYLIST_REQUEST';
export const DELETE_SONG_FROM_PLAYLIST_SUCCESS = 'DELETE_SONG_FROM_PLAYLIST_SUCCESS';
export const DELETE_SONG_FROM_PLAYLIST_ERROR = 'DELETE_SONG_FROM_PLAYLIST_ERROR';

export const UPDATE_PLAYLIST_REQUEST = 'UPDATE_PLAYLIST_REQUEST';
export const UPDATE_PLAYLIST_SUCCESS = 'UPDATE_PLAYLIST_SUCCESS';
export const UPDATE_PLAYLIST_ERROR = 'UPDATE_PLAYLIST_ERROR';

export const DELETE_PLAYLIST_REQUEST = 'DELETE_PLAYLIST_REQUEST';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_ERROR = 'DELETE_PLAYLIST_ERROR';

