// ActionType.js

export const CREATE_ALBUM_REQUEST = 'CREATE_ALBUM_REQUEST';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';
export const CREATE_ALBUM_ERROR = 'CREATE_ALBUM_ERROR';

export const GET_ALL_ALBUMS_REQUEST = 'GET_ALL_ALBUMS_REQUEST';
export const GET_ALL_ALBUMS_SUCCESS = 'GET_ALL_ALBUMS_SUCCESS';
export const GET_ALL_ALBUMS_ERROR = 'GET_ALL_ALBUMS_ERROR';

export const GET_ARTIST_ALBUMS_REQUEST = 'GET_ARTIST_ALBUMS_REQUEST';
export const GET_ARTIST_ALBUMS_SUCCESS = 'GET_ARTIST_ALBUMS_SUCCESS';
export const GET_ARTIST_ALBUMS_ERROR = 'GET_ARTIST_ALBUMS_ERROR';

export const FIND_ALBUM_REQUEST = 'FIND_ALBUM_REQUEST';
export const FIND_ALBUM_SUCCESS = 'FIND_ALBUM_SUCCESS';
export const FIND_ALBUM_ERROR = 'FIND_ALBUM_ERROR';

export const GET_ALBUM_TRACKS_REQUEST = 'GET_ALBUM_TRACKS_REQUEST';
export const GET_ALBUM_TRACKS_SUCCESS = 'GET_ALBUM_TRACKS_SUCCESS';
export const GET_ALBUM_TRACKS_ERROR = 'GET_ALBUM_TRACKS_ERROR';

export const UPLOAD_SONG_REQUEST = 'UPLOAD_SONG_REQUEST';
export const UPLOAD_SONG_SUCCESS = 'UPLOAD_SONG_SUCCESS';
export const UPLOAD_SONG_ERROR = 'UPLOAD_SONG_ERROR';

export const DELETE_ALBUM_REQUEST = 'DELETE_ALBUM_REQUEST';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_ERROR = 'DELETE_ALBUM_ERROR';
