export const CREATE_ALBUM_REQUEST = 'CREATE_ALBUM_REQUEST';
export const CREATE_ALBUM_ERROR = 'CREATE_ALBUM_ERROR';

export const GET_ALL_ALBUMS_REQUEST = 'GET_ALL_ALBUMS_REQUEST';
export const GET_ALL_ALBUMS_ERROR = 'GET_ALL_ALBUM_ERROR';

export const FIND_ALBUM_REQUEST = "FIND_ALBUM_REQUEST"
export const FIND_ALBUM_ERROR = "FIND_ALBUM_ERROR"