export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";

export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR";