export const GET_ALBUMS_RECOMMENDED_REQUEST = 'GET_ALBUMS_RECOMMENDED_REQUEST';
export const GET_ALBUMS_RECOMMENDED_SUCCESS = 'GET_ALBUMS_RECOMMENDED_SUCCESS';
export const GET_ALBUMS_RECOMMENDED_ERROR = 'GET_ALBUMS_RECOMMENDED_ERROR';

export const GET_ARTISTS_RECOMMENDED_REQUEST = 'GET_ARTISTS_RECOMMENDED_REQUEST';
export const GET_ARTISTS_RECOMMENDED_SUCCESS = 'GET_ARTISTS_RECOMMENDED_SUCCESS';
export const GET_ARTISTS_RECOMMENDED_ERROR = 'GET_ARTISTS_RECOMMENDED_ERROR';

export const GET_SONGS_RECOMMENDED_REQUEST = 'GET_SONGS_RECOMMENDED_REQUEST';
export const GET_SONGS_RECOMMENDED_SUCCESS = 'GET_SONGS_RECOMMENDED_SUCCESS';
export const GET_SONGS_RECOMMENDED_ERROR = 'GET_SONGS_RECOMMENDED_ERROR';