export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_ERROR = "CREATE_CHAT_ERROR";

export const GET_USERS_CHAT_REQUEST = "GET_USERS_CHAT_REQUEST";
export const GET_USERS_CHAT_SUCCESS = "GET_USERS_CHAT_SUCCESS";
export const GET_USERS_CHAT_ERROR = "GET_USERS_CHAT_ERROR";

export const DELETE_CHAT_REQUEST = "DELETE_CHAT_REQUEST";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_ERROR = "DELETE_CHAT_ERROR";