
export const FIND_ARTIST_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST"
export const FIND_ARTIST_BY_ID_ERROR = "FIND_USER_BY_ID_ERROR"

export const GET_ALL_ARTISTS_REQUEST = "GET_ALL_ARTISTS_REQUEST"
export const GET_ALL_ARTISTS_SUCCESS = "GET_ALL_ARTISTS_SUCCESS"
export const GET_ALL_ARTISTS_ERROR = "GET_ALL_ARTISTS_ERROR"
