
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";

export const GET_POST_COMMENT_REQUEST = "GET_POST_COMMENT_REQUEST";
export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS";
export const GET_POST_COMMENTS_FAIL = "GET_POST_COMMENTS_FAIL";

export const Like_COMMENT_REQUEST = "Like_COMMENT_REQUEST";
export const Like_COMMENT_SUCCESS = "Like_COMMENTS_SUCCESS";
export const Like_COMMENT_FAIL = "Like_COMMENT_FAIL";